global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'core_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'core-service:8080' ]
        labels:
          application: 'Core Service Application'
  - job_name: 'payment_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-service:8080' ]
        labels:
          application: 'Payment Service Application'
  - job_name: 'shipment_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'shipment-service:8080' ]
        labels:
          application: 'Shipment Service Application'